# GitHub Actions Workflow for Building OpenWRT Firmware

name: Build OpenWRT Firmware

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Target Device (e.g., s905x2, rk3328)'
        required: true
        default: 'h618-orangepi-zero3'
      kernel_version:
        description: 'Kernel Version (e.g., 6.1.104-AW64-DBAI)'
        required: true
        default: '6.1.104-AW64-DBAI'
      rootfs_url:
        description: 'URL to the rootfs file'
        required: true
        default: 'https://github.com/armarchindo/ULO-repository/raw/main/rootfs/openwrt-23.05.5-vanila-armsr-armv8-generic-ext4-rootfs.img.gz'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ULO-Builder
        run: |
          git clone https://github.com/armarchindo/ULO-Builder.git
          ROOTFS_FILENAME=$(basename "${{ github.event.inputs.rootfs_url }}")
          wget "${{ github.event.inputs.rootfs_url }}"
          mkdir -p ULO-Builder/rootfs
          mv "$ROOTFS_FILENAME" ULO-Builder/rootfs/

      - name: Run ULO-Builder
        run: |
          ROOTFS_FILENAME=$(basename "${{ github.event.inputs.rootfs_url }}")
          cd ULO-Builder
          sudo ./ulo -m ${{ github.event.inputs.target_device }} -r $ROOTFS_FILENAME -k ${{ github.event.inputs.kernel_version }} -s 1024
        